package View;

/**
 * The {@code Dashboard} class represents the main interface of the Forza Car Rental system.
 * <p>
 * It serves as the central navigation hub for the application, allowing staff members
 * to access core functionalities such as managing records, creating transactions,
 * and exiting the system.
 * </p>
 * <p>
 * This class is part of the View layer (V in MVC), focusing solely on the user interface
 * and delegating business logic to the Controller layer.
 * </p>
 *
 * <p><b>Features:</b></p>
 * <ul>
 *   <li>Displays system title and branding.</li>
 *   <li>Provides navigation buttons for major system operations.</li>
 *   <li>Includes basic UI enhancements such as hover effects and styled buttons.</li>
 * </ul>
 *
 * @author Galicia
 * @author Marcelino
 * @author Samarista
 * @author Sy
 * @version 1.0
 */

public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        footNote = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        manageRecords = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        createTransactions = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        getContentPane().setLayout(null);

        footNote.setFont(new java.awt.Font("Segoe UI Emoji", 2, 10)); // NOI18N
        footNote.setForeground(new java.awt.Color(255, 255, 255));
        footNote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footNote.setText("ALL RIGHTS RESERVED");
        getContentPane().add(footNote);
        footNote.setBounds(300, 400, 210, 16);

        title.setFont(new java.awt.Font("ROG Fonts", 3, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Forza Rentals");
        getContentPane().add(title);
        title.setBounds(140, 50, 540, 50);

        manageRecords.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        manageRecords.setText("RECORDS");
        manageRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRecordsActionPerformed(evt);
            }
        });
        getContentPane().add(manageRecords);
        manageRecords.setBounds(80, 200, 160, 30);

        exit.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(80, 300, 160, 30);

        createTransactions.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        createTransactions.setText("TRANSACTIONS");
        createTransactions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createTransactions.setMaximumSize(new java.awt.Dimension(72, 27));
        createTransactions.setMinimumSize(new java.awt.Dimension(72, 27));
        createTransactions.setPreferredSize(new java.awt.Dimension(72, 27));
        createTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTransactionsActionPerformed(evt);
            }
        });
        getContentPane().add(createTransactions);
        createTransactions.setBounds(80, 250, 160, 30);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 458, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CCINFOM FILES (2).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setAlignmentY(0.0F);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -40, 820, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTransactionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createTransactionsActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void manageRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRecordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createTransactions;
    private javax.swing.JButton exit;
    private javax.swing.JLabel footNote;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton manageRecords;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}