/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Lance
 */
public class ManageRecord extends javax.swing.JPanel {

    /**
     * Creates new form ManageRecord
     */
    public ManageRecord() {
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        manageDepartment = new javax.swing.JButton();
        manageJobs = new javax.swing.JButton();
        manageLocation = new javax.swing.JButton();
        manageBranch = new javax.swing.JButton();
        manageStaff = new javax.swing.JButton();
        manageRenter = new javax.swing.JButton();
        manageCar = new javax.swing.JButton();
        returnDashboard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(859, 460));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("ROG Fonts", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("MANAGE RECORDS");
        title.setToolTipText("");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 580, 40));

        jPanel1.setOpaque(false);

        manageDepartment.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        manageDepartment.setText("DEPARTMENTS");
        manageDepartment.setIconTextGap(0);
        manageDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDepartmentActionPerformed(evt);
            }
        });

        manageJobs.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        manageJobs.setText("JOBS");
        manageJobs.setIconTextGap(0);
        manageJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageJobsActionPerformed(evt);
            }
        });

        manageLocation.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        manageLocation.setText("LOCATIONS");
        manageLocation.setIconTextGap(0);
        manageLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLocationActionPerformed(evt);
            }
        });

        manageBranch.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        manageBranch.setText("BRANCHES");
        manageBranch.setIconTextGap(0);
        manageBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBranchActionPerformed(evt);
            }
        });

        manageStaff.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        manageStaff.setText("STAFF");
        manageStaff.setIconTextGap(0);
        manageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStaffActionPerformed(evt);
            }
        });

        manageRenter.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        manageRenter.setText("RENTERS");
        manageRenter.setIconTextGap(0);
        manageRenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRenterActionPerformed(evt);
            }
        });

        manageCar.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        manageCar.setText("CARS");
        manageCar.setToolTipText("");
        manageCar.setIconTextGap(0);
        manageCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCarActionPerformed(evt);
            }
        });

        returnDashboard.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        returnDashboard.setText("RETURN");
        returnDashboard.setToolTipText("");
        returnDashboard.setIconTextGap(0);
        returnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(manageCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(manageDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addComponent(manageStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageJobs, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(manageBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageRenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageJobs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageRenter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageCar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 510, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CCINFOM FILES (4).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 818, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageDepartmentActionPerformed

    private void manageJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageJobsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageJobsActionPerformed

    private void manageLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageLocationActionPerformed

    private void manageBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageBranchActionPerformed

    private void manageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageStaffActionPerformed

    private void manageRenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageRenterActionPerformed

    private void manageCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageCarActionPerformed

    private void returnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnDashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageBranch;
    private javax.swing.JButton manageCar;
    private javax.swing.JButton manageDepartment;
    private javax.swing.JButton manageJobs;
    private javax.swing.JButton manageLocation;
    private javax.swing.JButton manageRenter;
    private javax.swing.JButton manageStaff;
    private javax.swing.JButton returnDashboard;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
